### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hzoo** [hzoo/tppstats#1]
- [ ] refactor everything
- [x] update grunt
- [x] update socket.io, express
- [ ] babel: use generators
- [ ] remove `dist/` and be able to deploy
